spring.application.name=phone-security-api
server.port=5000

# Development database
#spring.datasource.url=jdbc:h2:file:./data/securitymonitor;AUTO_SERVER=TRUE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=root
#spring.datasource.password=rootroot

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.open-in-view=false

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:postgresql://asmdb.cezsigaamw2i.us-east-1.rds.amazonaws.com:5432/asmdb
spring.datasource.username=root
spring.datasource.password=rootroot

#spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# PostgreSQL production override example:
# SPRING_DATASOURCE_URL=jdbc:postgresql://HOST:5432/securitymonitor
# SPRING_DATASOURCE_USERNAME=...
# SPRING_DATASOURCE_PASSWORD=...
# SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
